/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.CrudJava.VIEW;

import br.com.CrudJava.CTR.CidadeCTR;
import br.com.CrudJava.CTR.ClienteCTR;
import br.com.CrudJava.CTR.EstadoCTR;
import br.com.CrudJava.CTR.SexoCTR;
import br.com.CrudJava.MODEL.CidadeMODEL;
import br.com.CrudJava.MODEL.EstadoMODEL;
import br.com.CrudJava.MODEL.SexoMODEL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class ClienteVIEW extends javax.swing.JFrame {
 
    String opcao;
    
     List<EstadoMODEL> estadoList = new ArrayList<>();
      List<SexoMODEL> sexoList = new ArrayList<>();
  public static List<CidadeMODEL> cidadeList = new ArrayList<>();
    /**
     * Creates new form ClienteVIEW
     */
    public ClienteVIEW() {
        initComponents();
        setLocationRelativeTo(null);
        
        CarregaComboEstado();
        CarregaComboSexo();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_novo = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_cod = new javax.swing.JTextField();
        lbl_cod = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        lbl_endereco = new javax.swing.JLabel();
        lbl_cidade = new javax.swing.JLabel();
        lbl_cpf = new javax.swing.JLabel();
        lbl_cep = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        lbl_estado = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JFormattedTextField();
        txt_cep = new javax.swing.JFormattedTextField();
        cmb_estado = new javax.swing.JComboBox<>();
        cmb_cidade = new javax.swing.JComboBox<>();
        txt_endereco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmb_sexo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_salvar.setText("Salvar");
        btn_salvar.setEnabled(false);
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_cod.setEditable(false);

        lbl_cod.setText("Codigo");

        lbl_nome.setText("Nome");

        lbl_endereco.setText("Endereço");

        lbl_cidade.setText("Cidade");

        lbl_cpf.setText("CPF");

        lbl_cep.setText("CEP");

        txt_nome.setEditable(false);

        lbl_estado.setText("Estado");

        txt_cpf.setEditable(false);
        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpf.setText("    .   .   -    ");

        txt_cep.setEditable(false);
        try {
            txt_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cmb_estado.setEnabled(false);
        cmb_estado.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_estadoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        cmb_cidade.setEnabled(false);

        txt_endereco.setEditable(false);

        jLabel1.setText("Sexo");

        cmb_sexo.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_cpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lbl_cep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_endereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btn_novo)
                        .addGap(10, 10, 10)
                        .addComponent(btn_salvar)
                        .addGap(10, 10, 10)
                        .addComponent(btn_alterar)
                        .addGap(10, 10, 10)
                        .addComponent(btn_excluir)
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_voltar)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_cidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_nome)
                                .addGap(13, 13, 13)
                                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_estado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lbl_cod)
                                .addGap(18, 18, 18)
                                .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cod)
                    .addComponent(jLabel1)
                    .addComponent(cmb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_estado))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cpf)
                    .addComponent(lbl_cep)
                    .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cidade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_endereco)
                    .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novo)
                    .addComponent(btn_salvar)
                    .addComponent(btn_alterar)
                    .addComponent(btn_excluir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(btn_voltar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed

        txt_cod.setEditable(false);
        txt_nome.setEditable(true);
        txt_cep.setEditable(true);
        txt_cpf.setEditable(true);
        txt_endereco.setEditable(true);
        cmb_cidade.setEnabled(true);
        cmb_estado.setEnabled(true);
        cmb_sexo.setEnabled(true);

        btn_alterar.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_novo.setEnabled(false);
        btn_salvar.setEnabled(true);
        jButton1.setEnabled(false);
        limpaCampos();
        opcao = "cadastrar";
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        txt_cod.setEditable(false);
        txt_nome.setEditable(true);
        txt_cep.setEditable(true);
        txt_cpf.setEditable(true);
        txt_endereco.setEditable(true);
        cmb_cidade.setEnabled(true);
        cmb_estado.setEnabled(true);
        cmb_sexo.setEnabled(true);

        btn_novo.setEnabled(false);
        btn_excluir.setEnabled(false);
        btn_alterar.setEnabled(false);
        btn_salvar.setEnabled(true);
        jButton1.setEnabled(false);
        opcao="alterar";
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed

        String[] options = new String[]{"Sim","Não"};

        Object ret = JOptionPane.showOptionDialog(null,"Tem certeza que deseja excluir o cliente: "+txt_nome.getText()+" ?","Aviso!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);

        if(ret.equals(JOptionPane.YES_OPTION)){ExcluirCliente();}
        limpaCampos();
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed

        opcao();
        limpaCampos();
        btn_novo.setEnabled(true);
        btn_excluir.setEnabled(true);
        btn_alterar.setEnabled(true);
        btn_salvar.setEnabled(false);
        jButton1.setEnabled(true);

        txt_cod.setEditable(false);
        txt_nome.setEditable(false);
        txt_cep.setEditable(false);
        txt_cpf.setEditable(false);
        txt_endereco.setEditable(false);
        cmb_cidade.setEnabled(false);
        cmb_estado.setEnabled(false);
        cmb_sexo.setEnabled(false);
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
      

        this.dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PesquisarClienteVIEW view =new PesquisarClienteVIEW();
        view.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmb_estadoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_estadoPopupMenuWillBecomeInvisible
     FiltraComboCidade(estadoList.get(cmb_estado.getSelectedIndex()).getCod());
    }//GEN-LAST:event_cmb_estadoPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteVIEW().setVisible(true);
            }
        });
    }

      
    public void limpaCampos(){
    
     txt_cod.setText("");
     txt_nome.setText("");
     txt_cep.setText("");
     txt_cpf.setText("");
     txt_endereco.setText("");
     cmb_cidade.setSelectedItem(null);
     cmb_estado.setSelectedItem(null);
     cmb_sexo.setSelectedItem(null);
        
    }
    
    public void opcao(){
    
    switch(opcao){
    
        case "alterar":
            
            AlterarCliente();
            opcao = "";
            break;
            
        case "cadastrar":
            
            CadastrarCliente();
               opcao = "";
            break;
    
    } 
    
    }
    
    
 
     
      public void AlterarCliente(){
          
    ClienteCTR clienteCtr = new ClienteCTR();
    CidadeMODEL cidadeModel = new CidadeMODEL();
    SexoMODEL sexoModel = new SexoMODEL();
    
     Integer cod = Integer.parseInt(txt_cod.getText());
    
     sexoModel.setCod(sexoList.get(cmb_sexo.getSelectedIndex()).getCod());
    
     cidadeModel.setCod_cidade(cidadeList.get(cmb_cidade.getSelectedIndex()).getCod_cidade());
     
     clienteCtr.SetFk_Sexo_Cliente(sexoModel);
     clienteCtr.SetFk_Cidade_Cliente(cidadeModel);
     clienteCtr.SetEndereco_Cliente(txt_endereco.getText());
     clienteCtr.SetCPF_Cliente(txt_cpf.getText());
     clienteCtr.SetCep_Cliente(txt_cep.getText());
     clienteCtr.SetNome_Cliente(txt_nome.getText());
     
    clienteCtr.AlterarCliente(cod);
 
    }
    
      public void CadastrarCliente(){
          
     ClienteCTR clienteCtr = new ClienteCTR();
    CidadeMODEL cidadeModel = new CidadeMODEL();
    SexoMODEL sexoModel = new SexoMODEL();
          
       sexoModel.setCod(sexoList.get(cmb_sexo.getSelectedIndex()).getCod());
    
     cidadeModel.setCod_cidade(cidadeList.get(cmb_cidade.getSelectedIndex()).getCod_cidade());
     
     clienteCtr.SetFk_Sexo_Cliente(sexoModel);
     clienteCtr.SetFk_Cidade_Cliente(cidadeModel);
     clienteCtr.SetEndereco_Cliente(txt_endereco.getText());
     clienteCtr.SetCPF_Cliente(txt_cpf.getText());
     clienteCtr.SetCep_Cliente(txt_cep.getText());
     clienteCtr.SetNome_Cliente(txt_nome.getText());
     
    clienteCtr.CadastrarCliente();
    
    
    }
     public void ExcluirCliente(){
         
      ClienteCTR clienteCtr = new ClienteCTR();
    
       Integer cod = Integer.parseInt(txt_cod.getText());
       
     clienteCtr.DeletarCliente(cod);

     }
     
     public void CarregaComboEstado(){
         
      
        
      cmb_estado.removeAllItems();
     ResultSet rs_estado;
     EstadoCTR estadoCtr = new EstadoCTR();
    rs_estado = estadoCtr.ListaEstado();
    
        try {
          
            while(rs_estado.next()){
            EstadoMODEL estadoModel = new EstadoMODEL();
            
            estadoModel.setCod(rs_estado.getInt("cod_estado"));
            estadoModel.setNome(rs_estado.getString("nome_estado"));
            estadoModel.setSigla(rs_estado.getString("sigla_estado"));
            
            estadoList.add(estadoModel);
      
               cmb_estado.addItem(estadoModel.getSigla());
          
            }
                
                } catch (SQLException ex) {
                    
            Logger.getLogger(ClienteVIEW.class.getName()).log(Level.SEVERE, null, ex);
       
                }
   
     }
     
       public void CarregaComboSexo(){
         
      
        
      cmb_sexo.removeAllItems();
     ResultSet rs_sexo;
     SexoCTR sexoCtr = new SexoCTR();
    rs_sexo = sexoCtr.ListaSexo();
    
        try {
          
            while(rs_sexo.next()){
            SexoMODEL sexoModel = new SexoMODEL();
            
            sexoModel.setCod(rs_sexo.getInt("cod_sexo"));
            sexoModel.setDescricao(rs_sexo.getString("descricao_sexo"));
           
            
            sexoList.add(sexoModel);
      
               cmb_sexo.addItem(sexoModel.getDescricao());
          
            }
                
                } catch (SQLException ex) {
                    
            Logger.getLogger(ClienteVIEW.class.getName()).log(Level.SEVERE, null, ex);
       
                }
     
       }
       
    public static void FiltraComboCidade(int cod_estado){
         
   
      cmb_cidade.removeAllItems();
     ResultSet rs_cidade;
     CidadeCTR cidadeCtr = new CidadeCTR();
    rs_cidade = cidadeCtr.ListaCidade(cod_estado);
    
        try {
          cidadeList.clear();
            while(rs_cidade.next()){
            CidadeMODEL cidadeModel = new CidadeMODEL();
            cidadeModel.setCod_cidade(rs_cidade.getInt("cod_cidade"));
            cidadeModel.setNome_cidade(rs_cidade.getString("nome_cidade"));
           
            
            cidadeList.add(cidadeModel);
      
               cmb_cidade.addItem(cidadeModel.getNome_cidade());
          
            }
                
                } catch (SQLException ex) {
                    
            Logger.getLogger(ClienteVIEW.class.getName()).log(Level.SEVERE, null, ex);
       
                }}
        
    
               public void CarregaComboCidade(){
         
      
        
      cmb_cidade.removeAllItems();
     ResultSet rs_cidade;
     CidadeCTR cidadeCtr = new CidadeCTR();
    rs_cidade = cidadeCtr.ListaTodaCidade();
    
        try {
          
            while(rs_cidade.next()){
            CidadeMODEL cidadeModel = new CidadeMODEL();
            
            cidadeModel.setCod_cidade(rs_cidade.getInt("cod_cidade"));
            cidadeModel.setNome_cidade(rs_cidade.getString("nome_cidade"));
           
            
            cidadeList.add(cidadeModel);
      
               cmb_cidade.addItem(cidadeModel.getNome_cidade());
          
            }
                
                } catch (SQLException ex) {
                    
            Logger.getLogger(ClienteVIEW.class.getName()).log(Level.SEVERE, null, ex);
       
                }
       }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_voltar;
    public static javax.swing.JComboBox<String> cmb_cidade;
    public static javax.swing.JComboBox<String> cmb_estado;
    public static javax.swing.JComboBox<String> cmb_sexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_cep;
    private javax.swing.JLabel lbl_cidade;
    private javax.swing.JLabel lbl_cod;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_endereco;
    private javax.swing.JLabel lbl_estado;
    private javax.swing.JLabel lbl_nome;
    public static javax.swing.JFormattedTextField txt_cep;
    public static javax.swing.JTextField txt_cod;
    public static javax.swing.JFormattedTextField txt_cpf;
    public static javax.swing.JTextField txt_endereco;
    public static javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}
