/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.CrudJava.VIEW;

import br.com.CrudJava.CTR.ItemPedidoCTR;
import br.com.CrudJava.CTR.PedidoCTR;
import br.com.CrudJava.CTR.ProdutoCTR;
import br.com.CrudJava.MODEL.PedidoMODEL;
import br.com.CrudJava.MODEL.ProdutoMODEL;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alunos
 */
public class ItemPedidoVIEW extends javax.swing.JFrame {

    /**
     * Creates new form ItemPedidoVIEW
     */
    
    ResultSet rs;
    int cod_pedido;
    PedidoVIEW obj = new PedidoVIEW();
    public ItemPedidoVIEW() {
        initComponents();
         setLocationRelativeTo(null);
         BtnBuscar();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_item = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_quantidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_item);

        jButton1.setText("voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_add.setText("add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        jLabel1.setText("QTDD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_add, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_add)
                    .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
       if(!txt_quantidade.getText().equals("")&&!txt_quantidade.getText().equals("0")){
        
        ItemPedidoCTR ctr = new ItemPedidoCTR();
        PedidoCTR ctr2 = new PedidoCTR();
        PedidoMODEL pedido = new PedidoMODEL();
        ProdutoMODEL produto = new ProdutoMODEL();
        
        int linha = tbl_item.getSelectedRow();
        cod_pedido = ctr2.BuscarNumPedido();
        
        pedido.setNum_pedido(cod_pedido);
        produto.setCodigo_produto(Integer.parseInt(String.valueOf(tbl_item.getValueAt(linha,0))));
        
        ctr.SetFk_Pedido(pedido);
        ctr.SetFk_Produto(produto);
        ctr.SetQuantidade(Integer.parseInt(txt_quantidade.getText()));
        ctr.CadastrarItemPedido();
       
       }else{JOptionPane.showMessageDialog(null,"Insira uma quantidade válida.");}
    }//GEN-LAST:event_btn_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemPedidoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemPedidoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemPedidoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemPedidoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemPedidoVIEW().setVisible(true);
            }
        });
    }
public void PreencheTabela(){
     
         try{
     
     
     String[] todos={"Código","Descrição do Produto","Unidade","Valor"};
     
     String[][] linhas ={};
  
     DefaultTableModel tm = new DefaultTableModel(linhas, todos){
     
     public boolean isCellEditTable(int rowIndex, int mColIndex){return false;}
     
     };
         
             Vector<Vector> dados = new Vector<>();
             
             while(rs.next()){
             
            
            
             Vector regVetor = new Vector();
             
             regVetor.add(rs.getInt("codigo_produto"));
             regVetor.add(rs.getString("descricao_produto"));
             regVetor.add(rs.getString("unidade"));
             regVetor.add(rs.getString("val_unit"));
             dados.add(regVetor);
             tm.addRow(regVetor);
  
             }
             tbl_item.setModel(tm);
         
         }catch(Exception e){
    

            System.out.println(e.getMessage());
        
    }
     
     
     }
    
  
    
    public void BuscarProduto(){
    
    ProdutoCTR ctr =new ProdutoCTR();
    
    ctr.SetDescricao_produto("");
    rs=ctr.BuscarProduto();
    
    PreencheTabela();

    }
    
    public void BtnBuscar(){
    
    BuscarProduto();
    
    if(tbl_item.getRowCount()>0){
    tbl_item.changeSelection(0, 0, false, false);
    
    }
    tbl_item.grabFocus();
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_item;
    private javax.swing.JTextField txt_quantidade;
    // End of variables declaration//GEN-END:variables
}
