/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.CrudJava.VIEW;

import br.com.CrudJava.CTR.ClienteCTR;
import br.com.CrudJava.MODEL.CidadeMODEL;
import br.com.CrudJava.MODEL.ClienteMODEL;
import br.com.CrudJava.MODEL.EstadoMODEL;
import br.com.CrudJava.MODEL.SexoMODEL;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leroy2
 */
public class PesquisarClienteVIEW extends javax.swing.JFrame {

       List<ClienteMODEL> clienteList = new ArrayList<>();
    ResultSet rs;
    public ClienteVIEW obj;
   
    
    
    public PesquisarClienteVIEW() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_pesquisa = new javax.swing.JLabel();
        txt_pesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cliente = new javax.swing.JTable();
        btn_Pesquisar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_pesquisa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_pesquisa.setText("Pesquisar:");

        txt_pesquisa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tbl_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_clienteMouseClicked(evt);
            }
        });
        tbl_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_clienteKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_cliente);

        btn_Pesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_Pesquisar.setText("Pesquisar");
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });

        btn_voltar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_pesquisa)
                                .addGap(147, 147, 147))
                            .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_Pesquisar)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_voltar)
                                .addGap(66, 66, 66))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_pesquisa)
                    .addComponent(btn_voltar))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_clienteMouseClicked
        if(evt.getClickCount() == 1){
 ClienteVIEW view = new ClienteVIEW();
     view.setVisible(true);
            int linha = tbl_cliente.getSelectedRow();

            obj.txt_cod.setText(String.valueOf(tbl_cliente.getValueAt(linha, 0)));
            obj.txt_nome.setText(String.valueOf(tbl_cliente.getValueAt(linha, 1)));
            obj.txt_cpf.setText(String.valueOf(tbl_cliente.getValueAt(linha, 3)));
            obj.txt_cep.setText(String.valueOf(tbl_cliente.getValueAt(linha, 7)));
            obj.txt_endereco.setText(String.valueOf(tbl_cliente.getValueAt(linha, 6)));
            obj.cmb_estado.setSelectedItem(clienteList.get(linha).getFk_cidade().getEstado().getSigla());
             obj.FiltraComboCidade(clienteList.get(linha).getFk_cidade().getEstado().getCod());
            obj.cmb_cidade.setSelectedItem(clienteList.get(linha).getFk_cidade().getNome_cidade());
            obj.cmb_sexo.setSelectedItem(clienteList.get(linha).getFk_sexo().getDescricao());
      
            this.dispose();

        }
    }//GEN-LAST:event_tbl_clienteMouseClicked

    private void tbl_clienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_clienteKeyPressed
     ClienteVIEW view = new ClienteVIEW();
     view.setVisible(true);
            int linha = tbl_cliente.getSelectedRow();

            obj.txt_cod.setText(String.valueOf(tbl_cliente.getValueAt(linha, 0)));
            obj.txt_nome.setText(String.valueOf(tbl_cliente.getValueAt(linha, 1)));
            obj.txt_cpf.setText(String.valueOf(tbl_cliente.getValueAt(linha, 3)));
            obj.txt_cep.setText(String.valueOf(tbl_cliente.getValueAt(linha, 7)));
            obj.txt_endereco.setText(String.valueOf(tbl_cliente.getValueAt(linha, 6)));
            obj.cmb_estado.setSelectedItem(clienteList.get(linha).getFk_cidade().getEstado().getSigla());
            obj.FiltraComboCidade(clienteList.get(linha).getFk_cidade().getEstado().getCod());
            obj.cmb_cidade.setSelectedItem(clienteList.get(linha).getFk_cidade().getNome_cidade());
            obj.cmb_sexo.setSelectedItem(clienteList.get(linha).getFk_sexo().getDescricao());
           
            this.dispose();
    }//GEN-LAST:event_tbl_clienteKeyPressed

    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
        BtnBuscar();
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed

        this.dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarClienteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarClienteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarClienteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarClienteVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarClienteVIEW().setVisible(true);
            }
        });
    }
  public void PreencheTabela(){
     
         try{
     
     
     String[] todos={"Código","Nome do Cliente","Sexo","CPF","Estado","Cidade","Endereço","Cep"};
     
     String[][] linhas ={};
  
     DefaultTableModel tm = new DefaultTableModel(linhas, todos){
     
     public boolean isCellEditTable(int rowIndex, int mColIndex){return false;}
     
     };
         
             Vector<Vector> dados = new Vector<>();
             
             while(rs.next()){
                 EstadoMODEL estadoModel =new EstadoMODEL();
                 ClienteMODEL clienteModel = new ClienteMODEL();
                 CidadeMODEL cidadeModel = new CidadeMODEL();
                 SexoMODEL sexoModel = new SexoMODEL();
                 
                 
            
             Vector regVetor = new Vector();
             
             regVetor.add(rs.getInt("codigo_cliente"));
             regVetor.add(rs.getString("nome_cliente"));
             regVetor.add(rs.getString("descricao_sexo"));
             regVetor.add(rs.getString("cpf"));
             regVetor.add(rs.getString("sigla_estado"));
             regVetor.add(rs.getString("nome_cidade"));
             regVetor.add(rs.getString("endereco"));
             regVetor.add(rs.getString("cep"));
             dados.add(regVetor);
             tm.addRow(regVetor);
             
            estadoModel.setCod(rs.getInt("cod_estado"));
            estadoModel.setSigla(rs.getString("sigla_estado"));
            
            cidadeModel.setEstado(estadoModel);
            cidadeModel.setCod_cidade(rs.getInt("cod_cidade"));
            cidadeModel.setNome_cidade(rs.getString("nome_cidade"));
            
            sexoModel.setCod(rs.getInt("cod_sexo"));
            sexoModel.setDescricao(rs.getString("descricao_sexo"));
            
            clienteModel.setFk_cidade(cidadeModel);
            clienteModel.setFk_sexo(sexoModel);
            clienteModel.setCep(rs.getString("cep"));
            clienteModel.setCodigo_cliente(rs.getInt("codigo_cliente"));
            clienteModel.setCpf(rs.getString("cpf"));
            clienteModel.setEndereco(rs.getString("endereco"));
            clienteModel.setNome_cliente(rs.getString("nome_cliente"));
          
            clienteList.add(clienteModel);
             }
             tbl_cliente.setModel(tm);
         
         }catch(Exception e){
    

            System.out.println(e.getMessage());
        
    }
     
     
     }
     public void BuscarCliente(){
    
    ClienteCTR ctr =new ClienteCTR();
    
    ctr.SetNome_Cliente(txt_pesquisa.getText());
    rs=ctr.BuscarCliente();
    
    PreencheTabela();
    
    
    
    }
      public void BtnBuscar(){
    
    BuscarCliente();
    
    if(tbl_cliente.getRowCount()>0){
    tbl_cliente.changeSelection(0, 0, false, false);
    
    }
    tbl_cliente.grabFocus();
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_pesquisa;
    private javax.swing.JTable tbl_cliente;
    private javax.swing.JTextField txt_pesquisa;
    // End of variables declaration//GEN-END:variables
}
