/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.CrudJava.VIEW;

import br.com.CrudJava.CTR.CidadeCTR;
import br.com.CrudJava.MODEL.CidadeMODEL;
import br.com.CrudJava.MODEL.EstadoMODEL;
import java.sql.Array;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alunos
 */
public class PesquisarCidadeVIEW extends javax.swing.JFrame {

    /**
     * Creates new form PesquisarCidadeVIEW
     */  
     List<CidadeMODEL> cidadeList = new ArrayList<>();
    ResultSet rs;
    public CidadeVIEW obj;
    
    public PesquisarCidadeVIEW() {
        initComponents();
        setLocationRelativeTo(null);
        
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cidade = new javax.swing.JTable();
        btn_voltar = new javax.swing.JButton();
        lbl_pesquisa = new javax.swing.JLabel();
        btn_Pesquisar = new javax.swing.JButton();
        txt_pesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_cidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_cidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_cidadeMouseClicked(evt);
            }
        });
        tbl_cidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_cidadeKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_cidade);

        btn_voltar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        lbl_pesquisa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_pesquisa.setText("Pesquisar:");

        btn_Pesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_Pesquisar.setText("Pesquisar");
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });

        txt_pesquisa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_pesquisa)
                                .addGap(147, 147, 147))
                            .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_Pesquisar)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_voltar)
                                .addGap(66, 66, 66))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_pesquisa)
                    .addComponent(btn_voltar))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_cidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cidadeMouseClicked
        if(evt.getClickCount() == 1){

            int linha = tbl_cidade.getSelectedRow();

            obj.txt_cod.setText(String.valueOf(tbl_cidade.getValueAt(linha, 0)));
            obj.txt_cidade.setText(String.valueOf(tbl_cidade.getValueAt(linha, 1)));
            
            obj.txt_estado.setSelectedItem(cidadeList.get(linha).getEstado().getSigla());

            this.dispose();

        }
    }//GEN-LAST:event_tbl_cidadeMouseClicked

    private void tbl_cidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_cidadeKeyPressed
        int linha = tbl_cidade.getSelectedRow();
CidadeVIEW view = new CidadeVIEW();
view.setVisible(true);
        obj.txt_cod.setText(String.valueOf(tbl_cidade.getValueAt(linha, 0)));
        obj.txt_cidade.setText(String.valueOf(tbl_cidade.getValueAt(linha, 1)));
        
         obj.txt_estado.setSelectedItem(cidadeList.get(linha).getEstado().getSigla());

        this.dispose();

    }//GEN-LAST:event_tbl_cidadeKeyPressed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
      
        this.dispose();

    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
        BtnBuscar();
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarCidadeVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarCidadeVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarCidadeVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarCidadeVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarCidadeVIEW().setVisible(true);
            }
        });
    }
  public void PreencheTabela(){
     
         try{
     
     
     String[] todos={"Código","Nome da Cidade","Estado"};
     
     String[][] linhas ={};
  
     DefaultTableModel tm = new DefaultTableModel(linhas, todos){
     
     public boolean isCellEditTable(int rowIndex, int mColIndex){return false;}
     
     };
         
             Vector<Vector> dados = new Vector<>();
             
             while(rs.next()){
                 EstadoMODEL estadoModel = new EstadoMODEL();
                 CidadeMODEL cidadeModel = new CidadeMODEL();
            
            
             Vector regVetor = new Vector();
             
             regVetor.add(rs.getInt("cod_cidade"));
             regVetor.add(rs.getString("nome_cidade"));
             regVetor.add(rs.getString("sigla_estado"));
             dados.add(regVetor);
             tm.addRow(regVetor);
             
            estadoModel.setCod(rs.getInt("cod_estado"));
            estadoModel.setSigla(rs.getString("sigla_estado"));
            
            cidadeModel.setEstado(estadoModel);
            cidadeModel.setCod_cidade(rs.getInt("cod_cidade"));
            cidadeModel.setNome_cidade(rs.getString("nome_cidade"));
            
          
            cidadeList.add(cidadeModel);
             }
             tbl_cidade.setModel(tm);
         
         }catch(Exception e){
    

            System.out.println(e.getMessage());
        
    }
     
     
     }
    
  
    
    public void BuscarCidade(){
    
    CidadeCTR ctr =new CidadeCTR();
    
    ctr.SetNomeCidade(txt_pesquisa.getText());
    rs=ctr.BuscarCidade();
    
    PreencheTabela();
    
    
    
    }
    
    public void BtnBuscar(){
    
    BuscarCidade();
    
    if(tbl_cidade.getRowCount()>0){
    tbl_cidade.changeSelection(0, 0, false, false);
    
    }
    tbl_cidade.grabFocus();
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_pesquisa;
    private javax.swing.JTable tbl_cidade;
    private javax.swing.JTextField txt_pesquisa;
    // End of variables declaration//GEN-END:variables
}
