/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.CrudJava.VIEW;

import br.com.CrudJava.CTR.EstadoCTR;
import br.com.CrudJava.CTR.SexoCTR;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alunos
 */
public class PesquisarSexoVIEW extends javax.swing.JFrame {

     ResultSet rs;
     String cod_sexo;
     public SexoVIEW obj;
        
    public PesquisarSexoVIEW() {
        initComponents();
         setLocationRelativeTo(null);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_voltar = new javax.swing.JButton();
        lbl_pesquisa = new javax.swing.JLabel();
        btn_Pesquisar = new javax.swing.JButton();
        txt_pesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sexo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btn_voltar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        lbl_pesquisa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_pesquisa.setText("Pesquisar:");

        btn_Pesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_Pesquisar.setText("Pesquisar");
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });

        txt_pesquisa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tbl_sexo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_sexo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sexoMouseClicked(evt);
            }
        });
        tbl_sexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_sexoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sexo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_pesquisa)
                                .addGap(147, 147, 147))
                            .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Pesquisar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_voltar)
                                .addGap(13, 13, 13)))
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_pesquisa)
                        .addGap(6, 6, 6)
                        .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_voltar)
                        .addGap(6, 6, 6)
                        .addComponent(btn_Pesquisar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
      
        this.dispose();

    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
        BtnBuscar();
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      txt_pesquisa.grabFocus();
    }//GEN-LAST:event_formWindowOpened

    private void tbl_sexoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_sexoKeyPressed
         int linha = tbl_sexo.getSelectedRow();

            obj.txt_cod.setText(String.valueOf(tbl_sexo.getValueAt(linha, 0)));
            obj.txt_descricao.setText(String.valueOf(tbl_sexo.getValueAt(linha, 1)));
            

            this.dispose();
    }//GEN-LAST:event_tbl_sexoKeyPressed

    private void tbl_sexoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sexoMouseClicked
                if(evt.getClickCount() == 1){

            int linha = tbl_sexo.getSelectedRow();

            obj.txt_cod.setText(String.valueOf(tbl_sexo.getValueAt(linha, 0)));
            obj.txt_descricao.setText(String.valueOf(tbl_sexo.getValueAt(linha, 1)));
            

            this.dispose();

        }
    }//GEN-LAST:event_tbl_sexoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarSexoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarSexoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarSexoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarSexoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarSexoVIEW().setVisible(true);
            }
        });
    }
    
     public void PreencheTabela(){
     
         try{
    
     
     String[] todos={"Código","Descrição"};
     
     String[][] linhas ={};
     
     DefaultTableModel tm = new DefaultTableModel(linhas, todos){
     
     public boolean isCellEditTable(int rowIndex, int mColIndex){return false;}
     
     };
     
             Vector<Vector> dados = new Vector<>();
             
             while(rs.next()){
             
             Vector regVetor = new Vector();
             
             regVetor.add(rs.getInt("cod_sexo"));
             regVetor.add(rs.getString("descricao_sexo"));
             dados.add(regVetor);
             tm.addRow(regVetor);
             
             }
             tbl_sexo.setModel(tm);
         
         }catch(Exception e){
    

            System.out.println(e.getMessage());
        
    }
     
     
     }
    
    public void SelecionaValor(){
    
    cod_sexo=String.valueOf(tbl_sexo.getValueAt(tbl_sexo.getSelectedRow(),0));
    this.dispose();
    
    }
    
    public void BuscarSexo(){
    
    SexoCTR ctr =new SexoCTR();
    
    ctr.SetDescricao(txt_pesquisa.getText());
   
   rs= ctr.BuscarSexo();
    
    PreencheTabela();
    
    
    
    }
    
    public void BtnBuscar(){
    
    BuscarSexo();
    
    if(tbl_sexo.getRowCount()>0){
    tbl_sexo.changeSelection(0, 0, false, false);
    
    }
    tbl_sexo.grabFocus();
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_pesquisa;
    private javax.swing.JTable tbl_sexo;
    private javax.swing.JTextField txt_pesquisa;
    // End of variables declaration//GEN-END:variables
}
